### ISSUE TITLE
Conan Test Failed

### ISSUE THREAD

**Issue by BDehury85** [HITS-MBM/conan#3]
I tried to run the test ..I got the following Error code:
Welcome to the CONAN test script. Fingers crossed!
Checking for gmx...FOUND
Checking for mencoder...FOUND
Checking for gnuplot...FOUND
sh: 1: Syntax error: Bad fd number
This file doesn't exist at all: aggregate/mdmat_average_rmsf.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/mdmat_average_rmsf.dat, file_b: aggregate/mdmat_average_rmsf.dat, errors:-1

Test 8: Asymmetric mode.... FAILED
7 test(s) failed. The output of the failed tests has been preserved.
It is possible that the deviations are minor.
The failures are in the following folders:
2_Pearson
3_ClusterTraj
4_ClusterRes
5_Blocking
6_PCA
7_Reread
8_Asymmetric

**Comment by csabadaday** [comment]
Hi,

I am sorry about this issue. It is a bash version question. I was going to change this but at the moment I am also changing conan.py so I cannot update the current version. In the meantime, could you try this alternative version of test.py?

Unzip this file and overwrite ~/conan/test/test.py with this one.

Sorry again!!

Best,
   Csaba
[test.zip](https://github.com/HITS-MBM/conan/files/3789042/test.zip)

**Comment by osercinoglu** [comment]
I'm facing the same issue. I've tried the alternative version of test.py you provided. What happens is the cursor turns into a crosshair and that's it. Nothing happens afterwards.

**Comment by csabadaday** [comment]
This is a shell version issue of the test module. I need to look into ways of having it more universal. In the meantime, could you let me know if you can actually run conan on random input files such as you can find on:

https://github.com/HITS-MBM/conan/blob/master/docs/Example_inputs.md

?

Sorry that I can't give you an easy solution right now.

**Comment by csabadaday** [comment]
Hi all,

I think I solved the issue. Could you try it with this test.py? I am trying the subprocess module from python. It seems to work on both bash and dash.

Sorry for the wait.

Best
   Csaba
[test.zip](https://github.com/HITS-MBM/conan/files/3802262/test.zip)

**Comment by BDehury85** [comment]
Dear Csaba,
Thank you so much its working now..Thanks a lot for your quick and prompt valuable input.

Thanks and regards
Budheswar

**Comment by csabadaday** [comment]
Hi Budheswar,

Really glad to hear that. I will update the test script right now and add the other features later.

Best,
  Csaba

**Comment by BDehury85** [comment]
Hi @csabadaday 
Is there any way I can use conan for my analysis of contacts between two chains of a protein ..If yes could you please help me how can I use conan for the same?

Thanks and regards
Budheswar

**Comment by csabadaday** [comment]
Yes it is possible. Check out "asymmetric mode" in the manual.

Basically, make sure you include NRES_X, START_X, and similarly NRES_Y and START_Y.

Make an index group including both chains and make sure you have the start of both chains correct. There's an example in the manual that will hopefully help.

**Comment by BDehury85** [comment]
@csabadaday Thanks a lot for your reply. I was looking for the "ZOOM_LIST all.txt" in the example. The text file is missing so I was wondering how can I prepare for my trajectories ..

I have created an index file for my two chains and rename them x and y ..

How can proceed for calculation..
Thanks and regards
Budheswar

**Comment by csabadaday** [comment]
ZOOM_LIST is for a few interesting residue pairs to be "zoomed in". It is described in the manual (https://github.com/HITS-MBM/conan/blob/master/docs/index.md) and an example list is in the example input files: https://github.com/HITS-MBM/conan/blob/master/example_input/zoom_list.txt

But as I said, you need to turn on "asymmetric mode" by using NRES_X, START_X, etc ... This is described in the manual, but I am happy to copy-paste it here as well.

From https://github.com/HITS-MBM/conan/blob/master/docs/index.md :

> **Example for an asymmetric run**
> Suppose we are working with a PDB of 3000 residues but want to analyze the contacts formed between residues 1001..1050 and residues 2001..2050 while keeping this numbering but ignoring all other pairs. We can proceed as follows:
> 
> We create a special index file for these residues only.
> In the .xpm file these appear as 1..50 and 51..100, respectively. The .xpm file will contain a symmetric matrix, but CONAN will ignore the "on-diagonal" parts.
> We set:
> START_X### 1
> NRES_X    50
> NTERM_X 1001
> START_Y   51
> NRES_Y    50
> NTERM_Y 2001
> Note that if we want to use a PDB file, conan.py will look for 1001..1050 and 2001..2050 in the residue ID column.

**Comment by csabadaday** [comment]
Suppose you have two chains that each contain 100 residues. Then, you'll have an index file with 200 residues: 1-100 for x, 101-200 for y. Then, you need to add
START_X 1
NRES_X 100
NTERM_X 1
START_Y 101
NRES_Y 100
NTERM_Y 1

**Comment by BDehury85** [comment]
@csabadaday Hi,
It is not clear from the supplementary file of MS, how can I use them for my trajectory is membrane component (lipid bilayer) which contains five chains :
let us say I want to compute the contact between chain B and E, how can I define in .inp file and zoom file:

Please check this in your supplementary file:
We began by running CONAN on the entire trajectory, uniting all atoms from each protein as to have the same
residue ID. We used this file (sys chains .gro) as a structure file for the contact analysis. all . txt contains all 28
possible chain pairs.
TRAJ traj.gro
COORD sys_chains.gro
NLEVEL 1000
TRUNC 1.00
TRUNC_INTER 0.3
TRUNC_INTER_HIGH 0.5
GNUS_PATH ~/CONAN/input_gnuplotscripts/
RUN_MDMAT yes
ZOOM_LIST all.txt
The output of CONAN in the “zoomed in” version was next used to generate interesting fragments of the
simulation time (any time at least 10 ns long where the interaction between the chains is uninterrupted), using
simple awk commands. For each of these interesting time fragments, CONAN was used on the particular 72-
residue fragment.
TRAJ traj.gro
COORD sys_chains.gro
NLEVEL 1000
TRUNC 1.00
INDEX index.ndx
TRUNC_INTER 0.5
TRUNC_INTER_HIGH 0.5
BEGIN <begin>
END <end>
GNUS_PATH ~/CONAN/input_gnuplotscripts/
RUN_MDMAT yes
ZOOM_LIST all.txt

to do my job I have created an index of chain B and E (index.ndx) where I have named then as chainB and chainE .
what would be my input:
TRAJ md.xtc
COORD md.tpr
INDEX index.ndx
NLEVEL 1501
DT 100
TRUNC 1.00
TRUNC_INTER 0.3
TRUNC_INTER_HIGH 0.5
GNUS_PATH ~/CONAN/input_gnuplotscripts/
RUN_MDMAT yes
ZOOM_LIST zoom_list.txt

The zoom list file looks like:
#Each line has two residue ID's...
73 467 #(for chain B)
1  39 # (for chain E)

Please suggest your input..

Thanks and regards
Budheswar

**Comment by csabadaday** [comment]
Dear Budheswar,

Please email me instead. This is an issue thread about the testing module.

csaba.daday@h-its.org

Best,
   Csaba

**Comment by BDehury85** [comment]
@csabadaday sorry..I will email you..
