### ISSUE TITLE
Problem with Scipy

### ISSUE THREAD

**Issue by almeida85** [HITS-MBM/conan#8]
Hello,
I updated my Conda to 24.11.1 with Scipy version=1.14.1.
When running Conan I get this error:
```
Traceback (most recent call last):
  File "/media/Data1/Softwares/conan-master/conan.py", line 15, in <module>
    from scipy import var
ImportError: cannot import name 'var' from 'scipy' (/opt/anaconda3/lib/python3.12/site-packages/scipy/__init__.py)
```
Looking at the scipy package, `var` is in several subpackages. Any idea how to fix this?

Thanks.

**Comment by dadayqsim** [comment]
Hi Yasser,

We are in the process of migrating this package so I can work on it soon. Until then I think just replacing "from scipy import var" with "from numpy import var" should work.

Sorry about this.

Csaba

**Comment by almeida85** [comment]
Thanks, it worked.
